export const indoorMatches = [
  // your matches hereexport const matches = [
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Rajnandam Patil (Civil)", "Amit Kadam (EE)"],
    departments: ["Civil", "EE"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Roshan Raut (IT)", "Viraj Chalake (Mech)"],
    departments: ["IT", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Omkar Patil (ENTC)", "Swarup Kumbhar (EE)"],
    departments: ["ENTC", "EE"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Soham Charan (IT)", "Pravin Rajge (ENTC)"],
    departments: ["IT", "ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Pramod Bhandare (ENTC)", "Athrav Suryawanshi (Civil)"],
    departments: ["ENTC", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Samanth Malge (Civil)", "Prathmesh Fulkargi (EE)"],
    departments: ["Civil", "EE"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Rutraj Chavan (ENTC)", "Pradum Jadhav (Mech)"],
    departments: ["ENTC", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Rehan Sayad (Civil)", "Kirtan Ramdhan (Civil)"],
    departments: ["Civil", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Sanket Adate (IT)", "Jagannath Sidam (Civil)"],
    departments: ["IT", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Sujal Daund (ENTC)", "Ronit Doshi (IT)"],
    departments: ["ENTC", "IT"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Roshan Mohod (IT)", "Adarsh Chavan (Mech)"],
    departments: ["IT", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Shivam Landage (Civil)", "Shiddesh Kumbhar (Mech)"],
    departments: ["Civil", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Pranav Patil (ENTC)", "Sandesh Ingale (ENTC)"],
    departments: ["ENTC", "ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Rohit Thorat (EE)", "Harshal Waghmare (IT)"],
    departments: ["EE", "IT"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Dishant Padalkar (IT)", "Yeshukesh Kale (IT)"],
    departments: ["IT", "IT"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Rushikesh Mali (Mech)", "Aryan Jadhav (Mech)"],
    departments: ["Mech", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Yogidam Mali (Mech)", "Yash Tanekar (ENTC)"],
    departments: ["Mech", "ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Omkar Gurav (EE)", "Digvijay Pathir (ENTC)"],
    departments: ["EE", "ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Ayush Gad (EE)", "Ayush Shende (ENTC)"],
    departments: ["EE", "ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Chandan (IT)", "Tejas Kadam (EE)"],
    departments: ["IT", "EE"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Pranav Chavan (ENTC)", "Sanskar Sonwane (ENTC)"],
    departments: ["ENTC", "ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Aditya Pardeshi (ENTC)", "Vedant Kulkarni (Mech)"],
    departments: ["ENTC", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },

  // Sigle Girls Matches

  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Aditi Patil (IT)", "Kasturi Gawali (IT)"],
    departments: ["IT", "IT"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Asiya Munali (Civil)", "Sonali Thorat (ENTC)"],
    departments: ["Civil", "ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Sharmila Nalwade (Mech)", "Prerna Hundekar (Civil)"],
    departments: ["Mech", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Saniya Raut (ENTC)", "Bhagyashri Patil (Mech)"],
    departments: ["ENTC", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Disha Vattak (Civil)", "Shraddha Chavate (Civil)"],
    departments: ["Civil", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Pallavi Thigale (Civil)", "Sakshi Shinde (ENTC)"],
    departments: ["Civil", "ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Purva Pakhale (IT)", "Rushika Gonjare (Civil)"],
    departments: ["IT", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Pratiksha Pawar (Civil)", "Vedika Patil (Civil)"],
    departments: ["Civil", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Siddhi Shinde (SY ENTC)", "Manasi Gawade (Mech)"],
    departments: ["ENTC", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Vedika Dhane (Civil)", "Kasturi Gawali (IT)"],
    departments: ["Civil", "IT"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Pradnya Uture (IT)", "Shamim Kazi (Civil)"],
    departments: ["IT", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Saloni Ghatage (Civil)", "Jagruti Bhonde (Mech)"],
    departments: ["Civil", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Shraddha Shirke (CE)", "Tejaswini Waghmode (Mech)"],
    departments: ["CE", "Mech"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Shreya Morkhe (Mech)", "Shweta Jadhav (IT)"],
    departments: ["Mech", "IT"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Swara Late (IT)", "Shruti Deshmukh (Civil)"],
    departments: ["IT", "Civil"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  },
  {
    sport: "Carrom",
    event: "Singles (Girls)",
    category: "Indoor Games",
    round: "Round 1",
    participants: ["Aditi Mane (ENTC)", "—"],
    departments: ["ENTC"],
    status: "Scheduled",
    result: "N/A",
    date: "2025-12-30",
    time: "N/A",
    timestamp: "2025-12-30"
  }

  
];


